In [2]:
import numpy as np

# Create a 1D array

In [7]:
myList = [1, 2, 3, 4, 5]

In [8]:
arr = np.array(myList)

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
arr2 = np.array(my_mat)

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10,2) # start, stop, step

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(3) 

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10) # start, stop, number of points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5) # random numbers between 0 and 1

array([0.49658501, 0.24495041, 0.29795479, 0.71094138, 0.56728637])

In [22]:
np.random.rand(5,4) # random numbers between 0 and 1 in a 5x4 matrix

array([[0.92304559, 0.47544368, 0.3133001 , 0.09055857],
       [0.41968174, 0.01609505, 0.48984578, 0.34081313],
       [0.02920253, 0.86620016, 0.48736264, 0.03187913],
       [0.83235847, 0.70929348, 0.73439724, 0.53359868],
       [0.93290408, 0.73595364, 0.34519497, 0.1576134 ]])

In [23]:
np.random.randn(5) # random numbers from a normal distribution

array([ 0.31566551, -1.39153485, -0.13975537,  0.86522491,  0.43443347])

In [24]:
np.random.randn(5,4) # random numbers from a normal distribution in a 5x4 matrix

array([[ 0.0950236 , -0.8052461 , -0.42522104,  1.30848103],
       [-1.29603551,  0.34867177, -0.883612  , -0.76091769],
       [-1.0579458 ,  0.76189235,  1.52130595, -2.18709022],
       [-0.66396525,  0.49210479, -0.66377613,  0.44139364],
       [ 0.4863637 ,  0.71994315, -1.30622918,  1.0099954 ]])

In [25]:
np.random.randint(1,100,20) # random integers between 1 and 100

array([22, 21, 50,  9, 29, 77, 64, 96, 83, 64, 75, 95, 24, 66, 79, 83, 34,
       33, 81, 74])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
randarr = np.random.randint(0,35,15)

In [30]:
randarr

array([30, 12, 20,  5,  9, 31,  3, 14, 15, 25, 24, 18, 13, 22, 33])

In [32]:
arr.reshape(5,5) # must have the same number of elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
randarr.reshape(3,5) # must have the same number of elements

array([[30, 12, 20,  5,  9],
       [31,  3, 14, 15, 25],
       [24, 18, 13, 22, 33]])

In [34]:
randarr.max() # maximum value

33

In [35]:
randarr.min() # minimum value

3

In [36]:
randarr.argmax() # index of the maximum value

14

In [37]:
randarr.argmin() # index of the minimum value

6

In [39]:
arr.shape # shape of the array

(25,)

In [40]:
randarr.shape # shape of the array

(15,)

In [41]:
arr.dtype # data type

dtype('int64')

In [42]:
randarr.dtype # data type

dtype('int64')

In [1]:
def max_desserts(N, required_quantities, current_stocks):
    max_desserts_possible = float('inf')

    for i in range(N):
        max_desserts_possible = min(max_desserts_possible, current_stocks[i] // required_quantities[i])

    return max_desserts_possible

# Read input
N = int(input())
required_quantities = list(map(int, input().split()))
current_stocks = list(map(int, input().split()))

# Calculate and print the maximum number of desserts
print(max_desserts(N, required_quantities, current_stocks))

KeyboardInterrupt: Interrupted by user