In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8] # get the value at index 8

8

In [5]:
arr[1:5] # start at index 1 and go up to but not include index 5

array([1, 2, 3, 4])

In [6]:
arr[4:] # same as arr[4:len(arr)]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[:5] # same as arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[0:3] = 20 # broadcast the value 20 to the first 3 elements

In [9]:
arr

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.arange(0,11)

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 22

In [14]:
slice_of_arr

array([22, 22, 22, 22, 22, 22])

In [15]:
arr # the original array is also changed

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

In [16]:
new_copied_arr = arr.copy()

In [17]:
new_copied_arr

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

In [18]:
new_copied_arr[:] = 99

In [19]:
new_copied_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [20]:
arr

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

# 2D array indexing

In [21]:
arr_2d = np.array(([5,10,15],[15,20,25],[25,30,35]))

In [22]:
arr_2d

array([[ 5, 10, 15],
       [15, 20, 25],
       [25, 30, 35]])

In [24]:
arr_2d[1][0] # get the value at row 1, column 0

15

In [25]:
arr_2d[1]

array([15, 20, 25])

In [26]:
arr_2d[1,0] # same as arr_2d[1][0]

15

In [27]:
arr_2d[:2,1:] # get the first two rows and the last two columns

array([[10, 15],
       [20, 25]])

In [29]:
arr_2d[1:,:2] # get the last row and the first two columns

array([[15, 20],
       [25, 30]])

In [30]:
arr = np.arange(1,11)

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
bool_arr = arr > 5 # get a boolean array

In [35]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
arr[bool_arr] # get the values that are True

array([ 6,  7,  8,  9, 10])

In [39]:
arr[arr < 3] # get the values that are less than 3

array([1, 2])

In [40]:
new_2d_arr = np.arange(30).reshape(5,6)

In [41]:
new_2d_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
new_2d_arr[1:4,1:5] # Note : Last index is not included

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22]])